/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "IncidentTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "RunbookTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Site": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "SlackBotToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SlackSigningSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "Web": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}